### ISSUE TITLE
Repeatable bug.

### ISSUE THREAD

**Issue by ShadedJon** [DevotedMC/BottledExperience#2]
1: Get over 25 levels.
2: Get three stacks of bottles in your inventory.
3: Only put one stack of bottles on your hotbar, put the rest in your main inventory. Fill the rest of your inventory up with random stuff.
4: If your inventory is full, and the empty bottles BE needs to take are not on your hotbar, BE will give you 1 stack of xp bottles, eat the rest of your experience, and leave you with empty bottles.

**Comment by ProgrammerDan** [comment]
Still needs testing but addressed by #3
